// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"home","path":"/home","access":"isUser","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"clients","path":"/clients","access":"isUser","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"deals","path":"/deals","access":"isUser","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"login","path":"/login","layout":false,"id":"5"},"6":{"name":"profile","path":"/profile","access":"isUser","parentId":"ant-design-pro-layout","id":"6"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Clients__index" */'@/pages/Clients/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Deals__index" */'@/pages/Deals/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Authentication__index" */'@/pages/Authentication/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Profile__index" */'@/pages/Profile/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'C:/Users/Lenovo/Desktop/DoNotTouch/БД/4/CRM-repo/crm/clientUmi1/crmCLient/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
